CREATE TABLE IF NOT EXISTS `user` (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  name VARCHAR (127) NOT NULL UNIQUE,
  password_hash VARCHAR (127) NOT NULL,

  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  deleted_at DATETIME(3) DEFAULT NULL,

  PRIMARY KEY (id)
) ENGINE = InnoDB ROW_FORMAT = DYNAMIC CHARSET = utf8mb4 COLLATE utf8mb4_bin;
